INSERT
  INTO tmp_ref_info
  (
    emitter_name,
    file_name,
    field_name,
    report_period_code,
    file_date,
    publish_date,
    auditor_name,
    factor,
    currency,
    tech_update_date
  )
VALUES
  (
    :emitter_name,
    :file_name,
    :field_name,
    :report_period_code,
    :file_date,
    :publish_date,
    :auditor_name,
    :factor,
    :currency,
    :tech_update_date
  )
