INSERT
  INTO tmp_double_dimension_statistic_period
  (
    emitter_name,
    file_name,
    report_type_code,
    item_horizontal_index,
    item_vertical_index,
    report_start_date,
    report_end_date,
    report_value,
    tech_update_date
  )
VALUES
  (
    :emitter_name,
    :file_name,
    :report_type_code,
    :item_horizontal_index,
    :item_vertical_index,
    :report_start_date,
    :report_end_date,
    :report_value,
    :tech_update_date
  )
